# Railway Deployment Configuration
# This file is used by Railway.app for deployment

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python bot.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
# Environment variables will be set in Railway dashboard
# TELEGRAM_BOT_TOKEN is required
