# Render.com Deployment Configuration
# This file can be used as reference, but configuration is done through Render dashboard

services:
  - type: web
    name: x-embeder-tg-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false  # Set this manually in Render dashboard
